"""Idempotent DEV-only synthetic data seeder.

Runs at api startup when ``DEV_MODE=True`` to create a usable demo
state on a fresh `docker compose up`: owner, period, categories,
sample transactions. Skipped entirely in production. Idempotent —
safe to run on every restart, only creates rows when the relevant
table is below a small threshold.

Why startup-time and not a one-shot script:
- Single command (``docker compose up``) gives the operator a
  working stack without manual onboarding clicks.
- ``./scripts/run-integration-tests.sh`` does ``compose down``
  which sometimes wipes ad-hoc data; restarting puts it back.

What it seeds (only if BD pretty empty — see _is_empty):
- 1 AppUser (matches ``OWNER_TG_ID``) with onboarded_at set.
- 1 active BudgetPeriod (current month, starting balance 100k ₽).
- 9 categories (8 expense + 1 income).
- 6 sample ActualTransactions with realistic Russian descriptions
  so AI categorization probes ("продукты пятёрочка" → Продукты)
  have something to match against, and AI chat tools (forecast,
  category summary) have non-zero data to reason over.

Embeddings are generated by the existing ``_init_missing_embeddings``
hook — we just create the categories.
"""
from __future__ import annotations

from datetime import date, datetime, timedelta, timezone

import structlog
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import (
    ActualSource,
    ActualTransaction,
    AppUser,
    BudgetPeriod,
    Category,
    CategoryKind,
    PeriodStatus,
    UserRole,
)
from app.db.session import AsyncSessionLocal, set_tenant_scope

logger = structlog.get_logger(__name__)


_DEFAULT_CATEGORIES: list[tuple[str, str, int]] = [
    # (name, kind, sort_order)
    ("Продукты", "expense", 10),
    ("Кафе и рестораны", "expense", 20),
    ("Транспорт", "expense", 30),
    ("Развлечения", "expense", 40),
    ("Здоровье", "expense", 50),
    ("Спорт", "expense", 60),
    ("Книги", "expense", 70),
    ("Подарки", "expense", 80),
    ("Зарплата", "income", 1),
]

# Sample tx descriptions chosen so common UAT probes land confidently
# on the right category (≥0.5 cosine threshold). Days-ago is relative
# to today inside the active period — keep ≤ today and ≥ period_start
# downstream when inserting.
_SAMPLE_TXNS: list[tuple[str, str, int, int]] = [
    # (description, category_name, amount_rub, days_ago)
    ("Продукты пятёрочка", "Продукты", 1500, 1),
    ("Обед в ресторане", "Кафе и рестораны", 950, 2),
    ("Такси домой", "Транспорт", 420, 0),
    ("Билеты в кино", "Развлечения", 800, 3),
    ("Аптека", "Здоровье", 1200, 1),
    ("Абонемент в зал", "Спорт", 2500, 5),
]


async def seed_dev_data(owner_tg_id: int) -> None:
    """Idempotently merge DEV-only synthetic data into the DB.

    No-op in non-DEV runs: caller must check ``settings.DEV_MODE`` first.
    Each step ("upsert"-style) only inserts what's missing — never
    overwrites or deletes — so running on a half-populated DB (e.g.
    leftovers from `./scripts/run-integration-tests.sh`) safely
    completes the picture without clobbering user data.
    """
    try:
        async with AsyncSessionLocal() as session:
            inserted: dict[str, int] = {
                "user": 0, "category": 0, "period": 0, "actual_tx": 0,
            }

            # 1. Owner — upsert by tg_user_id.
            user = (
                await session.execute(
                    select(AppUser).where(AppUser.tg_user_id == owner_tg_id)
                )
            ).scalar_one_or_none()
            if user is None:
                user = AppUser(
                    tg_user_id=owner_tg_id,
                    cycle_start_day=5,
                    onboarded_at=datetime.now(timezone.utc),
                    role=UserRole.owner,  # Phase 11 ROLE-01: dev seed создаёт owner
                )
                session.add(user)
                await session.flush()
                inserted["user"] = 1
            else:
                # Идемпотентно подравниваем поля для existing OWNER:
                if user.onboarded_at is None:
                    user.onboarded_at = datetime.now(timezone.utc)
                # Phase 11: гарантируем role=owner на DEV-seed (миграция backfill'ит
                # тот же row, но если миграция запускалась раньше создания юзера —
                # дополнительная страховка).
                if user.role != UserRole.owner:
                    user.role = UserRole.owner

            # Phase 11 multi-tenancy: domain tables (category, budget_period,
            # actual_transaction) carry NOT NULL user_id + RLS policies.
            # Without app.current_user_id GUC, INSERTs from the budget_app role
            # are blocked with "new row violates row-level security policy".
            # Set scope once per session — covers every domain INSERT below.
            user_pk = user.id
            await set_tenant_scope(session, user_pk)

            # 2. Active period — create one if none exists.
            today = date.today()
            period_start = today.replace(day=1)
            if period_start.month == 12:
                next_month_start = period_start.replace(
                    year=period_start.year + 1, month=1
                )
            else:
                next_month_start = period_start.replace(
                    month=period_start.month + 1
                )
            period_end = next_month_start - timedelta(days=1)

            period = (
                await session.execute(
                    select(BudgetPeriod)
                    .where(BudgetPeriod.status == PeriodStatus.active)
                    .where(BudgetPeriod.user_id == user_pk)
                    .limit(1)
                )
            ).scalar_one_or_none()
            if period is None:
                period = BudgetPeriod(
                    period_start=period_start,
                    period_end=period_end,
                    starting_balance_cents=10_000_000,
                    status=PeriodStatus.active,
                    user_id=user_pk,
                )
                session.add(period)
                await session.flush()
                inserted["period"] = 1
            else:
                period_start = period.period_start

            # 3. Categories — insert only missing names (scoped to this user).
            existing_names = {
                row[0] for row in (
                    await session.execute(
                        select(Category.name).where(Category.user_id == user_pk)
                    )
                ).all()
            }
            cats_by_name: dict[str, Category] = {}
            for name, kind, sort_order in _DEFAULT_CATEGORIES:
                if name in existing_names:
                    continue
                cat = Category(
                    name=name,
                    kind=CategoryKind(kind),
                    sort_order=sort_order,
                    user_id=user_pk,
                )
                session.add(cat)
                cats_by_name[name] = cat
                inserted["category"] += 1
            await session.flush()
            # Re-fetch lookup including pre-existing rows (scoped to user).
            for row in (
                await session.execute(
                    select(Category)
                    .where(Category.is_archived.is_(False))
                    .where(Category.user_id == user_pk)
                )
            ).scalars():
                cats_by_name.setdefault(row.name, row)

            # 4. Sample transactions — only when zero exist for this period.
            actual_count = (
                await session.execute(
                    select(func.count())
                    .select_from(ActualTransaction)
                    .where(ActualTransaction.period_id == period.id)
                )
            ).scalar_one()
            if actual_count == 0:
                for desc, cat_name, rub, days_ago in _SAMPLE_TXNS:
                    cat = cats_by_name.get(cat_name)
                    if cat is None:
                        continue
                    tx_date = today - timedelta(days=days_ago)
                    if tx_date < period_start:
                        tx_date = period_start
                    session.add(
                        ActualTransaction(
                            period_id=period.id,
                            kind=cat.kind,
                            amount_cents=rub * 100,
                            description=desc,
                            category_id=cat.id,
                            tx_date=tx_date,
                            source=ActualSource.mini_app,
                            user_id=user_pk,
                        )
                    )
                    inserted["actual_tx"] += 1
                salary_cat = cats_by_name.get("Зарплата")
                if salary_cat is not None:
                    session.add(
                        ActualTransaction(
                            period_id=period.id,
                            kind=salary_cat.kind,
                            amount_cents=15_000_000,
                            description="Зарплата за месяц",
                            category_id=salary_cat.id,
                            tx_date=period_start,
                            source=ActualSource.mini_app,
                            user_id=user_pk,
                        )
                    )
                    inserted["actual_tx"] += 1

            await session.commit()
            if any(inserted.values()):
                logger.info("dev.seed.merged", **inserted)
            else:
                logger.info("dev.seed.noop", reason="db_already_complete")
    except Exception:
        logger.warning("dev.seed.failed", exc_info=True)
