import CoreGraphics
// AUTO-GENERATED by scripts/gen-tokens.ts — do not edit.
import SwiftUI

enum PosterTokens {
    enum Color {
        static let cream = SwiftUI.Color(hex: "F4EAD9")
        static let ink = SwiftUI.Color(hex: "1B1A18")
        static let paper = SwiftUI.Color(hex: "FFF6E8")
        static let black = SwiftUI.Color(hex: "0E0E0E")
        static let coral = SwiftUI.Color(hex: "FF5A3C")
        static let cobalt = SwiftUI.Color(hex: "1B2A6B")
        static let yellow = SwiftUI.Color(hex: "FFE76E")
        static let red = SwiftUI.Color(hex: "C24A2A")
    }
    enum Space {
        static let s4: CGFloat = 4
        static let s8: CGFloat = 8
        static let s10: CGFloat = 10
        static let s12: CGFloat = 12
        static let s14: CGFloat = 14
        static let s18: CGFloat = 18
        static let s22: CGFloat = 22
        static let s24: CGFloat = 24
        static let s28: CGFloat = 28
        static let s40: CGFloat = 40
        static let s56: CGFloat = 56
    }
    enum Radius {
        static let none: CGFloat = 0
        static let device: CGFloat = 48
    }
    enum FontSize {
        static let eye: CGFloat = 11
        static let monoSm: CGFloat = 11
        static let bodySm: CGFloat = 12
        static let body: CGFloat = 13
        static let monoMd: CGFloat = 14
        static let italicMd: CGFloat = 17
        static let displaySm: CGFloat = 28
        static let display: CGFloat = 88
        static let mass: CGFloat = 88
        static let massItalic: CGFloat = 70
    }
    enum Font {
        static let archivoBlack = "Archivo Black"
        static let dmSerifItalic = "DM Serif Display"
        static let ptSerifItalic = "PT Serif"
        static let manrope = "Manrope Variable"
        static let jetBrainsMono = "JetBrains Mono Variable"
        static let posterSerifItalic = "PosterSerifItalic"
    }
    enum Easing {
        static let easeOutControl = (c0x: 0.22, c0y: 0.61, c1x: 0.36, c1y: 1)
        static let overshootControl = (c0x: 0.34, c0y: 1.56, c1x: 0.64, c1y: 1)
        static let sheetEaseControl = (c0x: 0.32, c0y: 0.72, c1x: 0, c1y: 1)
    }
    enum Shadow {
        static let tabBar = (x: CGFloat(0), y: CGFloat(12), blur: CGFloat(30), opacity: 0.45)
        static let fab = (x: CGFloat(0), y: CGFloat(6), blur: CGFloat(16), opacity: 0.35)
        static let thumb = (x: CGFloat(0), y: CGFloat(2), blur: CGFloat(6), opacity: 0.25)
    }
}

// MARK: - Theme enum (multi-theme support, Phase 50)

enum Theme: String, CaseIterable {
    case maximalPoster = "maximal_poster"

    /// Любой неизвестный raw (в т.ч. stale persisted "liquid_glass"/"ios_default"
    /// из прежних версий) безопасно резолвится в .maximalPoster.
    static func resolve(_ raw: String) -> Theme {
        Theme(rawValue: raw) ?? .maximalPoster
    }

    var ruLabel: String {
        switch self {
        case .maximalPoster: return "MAXIMAL POSTER"
        }
    }
}

// MARK: - Per-theme token enums

enum LiquidGlassTokens {
    static let bgPrimary = SwiftUI.Color(hex: "F2F2F7")
    static let glassTintLight = SwiftUI.Color.white.opacity(0.72)
    static let glassTintDark = SwiftUI.Color(.sRGB, red: 28.0 / 255, green: 28.0 / 255, blue: 30.0 / 255, opacity: 0.72)
    static let glassBorder = SwiftUI.Color.white.opacity(0.18)
    static let textPrimary = SwiftUI.Color(hex: "1C1C1E")
    static let textSecondary = SwiftUI.Color(.sRGB, red: 60.0 / 255, green: 60.0 / 255, blue: 67.0 / 255, opacity: 0.6)
    static let textTertiary = SwiftUI.Color(.sRGB, red: 60.0 / 255, green: 60.0 / 255, blue: 67.0 / 255, opacity: 0.3)

    static let shadowElevatedRadius: CGFloat = 8
    static let shadowFloatingRadius: CGFloat = 24
    static let shadowFloatingStrongRadius: CGFloat = 48

    enum FontSize {
        static let largeTitle: CGFloat = 34
        static let title1: CGFloat = 28
        static let title2: CGFloat = 22
        static let title3: CGFloat = 20
        static let headline: CGFloat = 17
        static let body: CGFloat = 17
        static let callout: CGFloat = 16
        static let subhead: CGFloat = 15
        static let footnote: CGFloat = 13
        static let caption1: CGFloat = 12
        static let caption2: CGFloat = 11
    }

    enum Radius {
        static let card: CGFloat = 14
        static let sheet: CGFloat = 16
        static let button: CGFloat = 12
        static let pill: CGFloat = 999
    }

    enum Motion {
        // iOS native: SwiftUI .smooth, .snappy, .bouncy
        // Mapping: springDefault → .smooth(duration: 0.32)
        //          springBouncy  → .bouncy(duration: 0.5)
        //          easeDecel     → .smooth(extraBounce: 0)
        static let fastDuration: Double = 0.2
        static let mediumDuration: Double = 0.32
        static let slowDuration: Double = 0.5
    }
}

enum IOSDefaultTokens {
    static let bgPrimary = SwiftUI.Color(hex: "F2F2F7")
    static let textPrimary = SwiftUI.Color(hex: "000000")
    static let tint = SwiftUI.Color(hex: "007AFF")
}

extension SwiftUI.Color {
    init(hex: String) {
        var s = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        if s.count == 6 { s += "FF" }
        let v = UInt64(s, radix: 16) ?? 0xFF5A_3CFF
        self.init(
            .sRGB,
            red: Double((v >> 24) & 0xFF) / 255,
            green: Double((v >> 16) & 0xFF) / 255,
            blue: Double((v >> 8) & 0xFF) / 255,
            opacity: Double(v & 0xFF) / 255)
    }
}
