// AUTO-GENERATED by scripts/gen-tokens.ts — do not edit.
import SwiftUI
import CoreGraphics

enum PosterTokens {
    enum Color {
        static let cream = SwiftUI.Color(hex: "F4EAD9")
        static let ink = SwiftUI.Color(hex: "1B1A18")
        static let paper = SwiftUI.Color(hex: "FFF6E8")
        static let black = SwiftUI.Color(hex: "0E0E0E")
        static let coral = SwiftUI.Color(hex: "FF5A3C")
        static let cobalt = SwiftUI.Color(hex: "1B2A6B")
        static let yellow = SwiftUI.Color(hex: "FFE76E")
        static let red = SwiftUI.Color(hex: "C24A2A")
    }
    enum Space {
        static let s4: CGFloat = 4
        static let s8: CGFloat = 8
        static let s10: CGFloat = 10
        static let s12: CGFloat = 12
        static let s14: CGFloat = 14
        static let s18: CGFloat = 18
        static let s22: CGFloat = 22
        static let s24: CGFloat = 24
        static let s28: CGFloat = 28
        static let s40: CGFloat = 40
        static let s56: CGFloat = 56
    }
    enum Radius {
        static let none: CGFloat = 0
        static let device: CGFloat = 48
    }
    enum FontSize {
        static let eye: CGFloat = 11
        static let monoSm: CGFloat = 11
        static let bodySm: CGFloat = 12
        static let body: CGFloat = 13
        static let monoMd: CGFloat = 14
        static let italicMd: CGFloat = 17
        static let displaySm: CGFloat = 28
        static let display: CGFloat = 88
        static let mass: CGFloat = 88
        static let massItalic: CGFloat = 70
    }
    enum Font {
        static let archivoBlack = "Archivo Black"
        static let dmSerifItalic = "DM Serif Display"
        static let ptSerifItalic = "PT Serif"
        static let manrope = "Manrope Variable"
        static let jetBrainsMono = "JetBrains Mono Variable"
        static let posterSerifItalic = "PosterSerifItalic"
    }
    enum Easing {
        static let easeOutControl = (c0x: 0.22, c0y: 0.61, c1x: 0.36, c1y: 1)
        static let overshootControl = (c0x: 0.34, c0y: 1.56, c1x: 0.64, c1y: 1)
        static let sheetEaseControl = (c0x: 0.32, c0y: 0.72, c1x: 0, c1y: 1)
    }
    enum Shadow {
        static let tabBar = (x: CGFloat(0), y: CGFloat(12), blur: CGFloat(30), opacity: 0.45)
        static let fab = (x: CGFloat(0), y: CGFloat(6), blur: CGFloat(16), opacity: 0.35)
        static let thumb = (x: CGFloat(0), y: CGFloat(2), blur: CGFloat(6), opacity: 0.25)
    }
}

extension SwiftUI.Color {
    init(hex: String) {
        var s = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        if s.count == 6 { s += "FF" }
        let v = UInt64(s, radix: 16) ?? 0xFF5A3CFF
        self.init(.sRGB,
                  red:   Double((v >> 24) & 0xFF) / 255,
                  green: Double((v >> 16) & 0xFF) / 255,
                  blue:  Double((v >>  8) & 0xFF) / 255,
                  opacity: Double( v        & 0xFF) / 255)
    }
}
