#!/usr/bin/env tsx
// AUTO-GENERATED outputs do NOT edit by hand. Edit design/tokens.json + this script.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Portable script-dir resolver (tsx may load as CJS or ESM depending on Node version).
const meta = import.meta as { dirname?: string; url?: string };
const SCRIPT_DIR = meta.dirname ?? (meta.url ? dirname(fileURLToPath(meta.url)) : __dirname);
const ROOT = join(SCRIPT_DIR, '..');
const SRC = join(ROOT, 'design/tokens.json');
const OUT_CSS = join(ROOT, 'frontend/src/stylesV10/tokens.css');
const OUT_SWIFT = join(ROOT, 'ios/BudgetPlanner/FeaturesV10/Common/PosterTokens.swift');

type Tokens = {
  version: string;
  color: Record<string, string>;
  spacing: Record<string, number>;
  radius: Record<string, number>;
  shadow: Record<string, string>;
  font: Record<string, string>;
  fontSize: Record<string, number>;
  letterSpacing: Record<string, string>;
  easing: Record<string, string>;
};

const t: Tokens = JSON.parse(readFileSync(SRC, 'utf8'));

// ---------- helpers ----------
const kebab = (s: string) => s.replace(/([A-Z])/g, '-$1').toLowerCase();
const entries = <T,>(obj: Record<string, T>) => Object.entries(obj);

// ---------- CSS emit ----------
const cssLines: string[] = ['/* AUTO-GENERATED by scripts/gen-tokens.ts — do not edit. */', ':root {'];
for (const [k, v] of entries(t.color))         cssLines.push(`  --poster-${kebab(k)}: ${v};`);
for (const [k, v] of entries(t.spacing))       cssLines.push(`  --poster-space-${k.replace(/^s/, '')}: ${v}px;`);
for (const [k, v] of entries(t.radius))        cssLines.push(`  --poster-radius-${kebab(k)}: ${v}px;`);
for (const [k, v] of entries(t.shadow))        cssLines.push(`  --poster-shadow-${kebab(k)}: ${v};`);
for (const [k, v] of entries(t.font))          cssLines.push(`  --poster-font-${kebab(k)}: '${v}';`);
for (const [k, v] of entries(t.fontSize))      cssLines.push(`  --poster-font-size-${kebab(k)}: ${v}px;`);
for (const [k, v] of entries(t.letterSpacing)) cssLines.push(`  --poster-tracking-${kebab(k)}: ${v};`);
for (const [k, v] of entries(t.easing))        cssLines.push(`  --poster-easing-${kebab(k)}: ${v};`);
cssLines.push('}', '');
mkdirSync(dirname(OUT_CSS), { recursive: true });
writeFileSync(OUT_CSS, cssLines.join('\n'));

// ---------- Swift emit ----------
const swiftLines: string[] = [
  '// AUTO-GENERATED by scripts/gen-tokens.ts — do not edit.',
  'import SwiftUI',
  'import CoreGraphics',
  '',
  'enum PosterTokens {',
  '    enum Color {',
  ...entries(t.color).map(([k, v]) =>
    `        static let ${k} = SwiftUI.Color(hex: "${v.replace('#', '')}")`),
  '    }',
  '    enum Space {',
  ...entries(t.spacing).map(([k, v]) =>
    `        static let ${k}: CGFloat = ${v}`),
  '    }',
  '    enum Radius {',
  ...entries(t.radius).map(([k, v]) =>
    `        static let ${k}: CGFloat = ${v}`),
  '    }',
  '    enum FontSize {',
  ...entries(t.fontSize).map(([k, v]) =>
    `        static let ${k}: CGFloat = ${v}`),
  '    }',
  '    enum Font {',
  ...entries(t.font).map(([k, v]) =>
    `        static let ${k} = "${v}"`),
  '    }',
  '    enum Easing {',
  ...entries(t.easing).map(([k, v]) => {
    // parse "cubic-bezier(0.22, 0.61, 0.36, 1)" → control points
    const m = v.match(/cubic-bezier\(([^)]+)\)/);
    const [c0x, c0y, c1x, c1y] = (m?.[1] ?? '0,0,1,1').split(',').map(s => s.trim());
    return `        static let ${k}Control = (c0x: ${c0x}, c0y: ${c0y}, c1x: ${c1x}, c1y: ${c1y})`;
  }),
  '    }',
  '    enum Shadow {',
  ...entries(t.shadow).map(([k, v]) => {
    // parse "0 12px 30px rgba(0,0,0,0.45)" → x, y, blur, opacity
    const m = v.match(/(-?\d+)(?:px)?\s+(-?\d+)(?:px)?\s+(-?\d+)(?:px)?\s+rgba?\(([^)]+)\)/);
    const [x, y, blur] = m ? [m[1], m[2], m[3]] : ['0', '0', '0'];
    const opacity = m ? (m[4].split(',').pop() || '0').trim() : '0';
    return `        static let ${k} = (x: CGFloat(${x}), y: CGFloat(${y}), blur: CGFloat(${blur}), opacity: ${opacity})`;
  }),
  '    }',
  '}',
  '',
  'extension SwiftUI.Color {',
  '    init(hex: String) {',
  '        var s = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)',
  '        if s.count == 6 { s += "FF" }',
  '        let v = UInt64(s, radix: 16) ?? 0xFF5A3CFF',
  '        self.init(.sRGB,',
  '                  red:   Double((v >> 24) & 0xFF) / 255,',
  '                  green: Double((v >> 16) & 0xFF) / 255,',
  '                  blue:  Double((v >>  8) & 0xFF) / 255,',
  '                  opacity: Double( v        & 0xFF) / 255)',
  '    }',
  '}',
  '',
];
mkdirSync(dirname(OUT_SWIFT), { recursive: true });
writeFileSync(OUT_SWIFT, swiftLines.join('\n'));

console.log('✓ tokens.css and PosterTokens.swift regenerated');
